name: bad_words
description: A dart filter for bad words. This filter will allow you to make a simple check to tell if a string contains bad words as defined in the lib/word_list.dart file.
version: 0.3.0
homepage: https://github.com/TylerSustare/dart_bad_words

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies: 
  test: ^1.20.1
